# shellcheck shell=bash
post_install() {
    cp /usr/share/rustdesk/files/rustdesk.service /etc/systemd/system/rustdesk.service
    cp /usr/share/rustdesk/files/rustdesk.desktop /usr/share/applications/
    cp /usr/share/rustdesk/files/rustdesk-link.desktop /usr/share/applications/
    systemctl daemon-reload
    systemctl enable rustdesk
    systemctl start rustdesk
    update-desktop-database
}

pre_upgrade() {
    systemctl stop rustdesk || true
}

post_upgrade() {
    cp /usr/share/rustdesk/files/rustdesk.service /etc/systemd/system/rustdesk.service
    cp /usr/share/rustdesk/files/rustdesk.desktop /usr/share/applications/
    cp /usr/share/rustdesk/files/rustdesk-link.desktop /usr/share/applications/
    systemctl daemon-reload
    systemctl enable rustdesk
    systemctl start rustdesk
    update-desktop-database
}

pre_remove() {
    systemctl stop rustdesk || true
    systemctl disable rustdesk || true
    rm /etc/systemd/system/rustdesk.service || true
}

post_remove() {
    rm /usr/share/applications/rustdesk.desktop || true
    rm /usr/share/applications/rustdesk-link.desktop || true
    update-desktop-database
}
