#!/bin/bash
# shellcheck disable=SC2034,SC2154
# Colored makepkg-like functions
note() {
    printf "${_blue}==>${_yellow} NOTE:${_bold} %s${_all_off}\n" "$1"
}

_all_off="$(tput sgr0)"
_bold="${_all_off}$(tput bold)"
_blue="${_bold}$(tput setaf 4)"
_yellow="${_bold}$(tput setaf 3)"

post_install() {
    note "The TeamViewer daemon must be running for TeamViewer to work."
    note "Enable and start it with: sudo systemctl enable --now teamviewerd"
}

post_upgrade() {
    post_install
}

post_remove() {
    rm -rf /opt/teamviewer
}
