[project]
name = "tmp-kiro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fredrik Angelsen", email = "fredrikangelsen@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "awscrt>=0.28.2",
    "boto3>=1.40.52",
    "mitmproxy>=12.1.2",
]

[project.scripts]
tmp-kiro = "tmp_kiro:main"

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"
